import 'package:asset_guard/asset_guard.dart';
import 'package:test/test.dart';

import 'support/fixture.dart';

void main() {
  late FixtureProject project;

  setUp(() => project = FixtureProject.create());
  tearDown(() => project.dispose());

  test('same image at a different size is labelled SCALED_VARIANT', () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/images/']))
      ..png('assets/images/hero.png', width: 64, height: 64)
      ..png('assets/images/hero_small.png', width: 32, height: 32)
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);
    final scaled = findingsWithCode(result, FindingCode.scaledVariant);

    expect(scaled, hasLength(1));
    expect(
      <String?>[scaled.single.path, ...scaled.single.relatedPaths],
      <String>['assets/images/hero.png', 'assets/images/hero_small.png'],
    );
    expect(scaled.single.data['dimensions'], <String, String>{
      'assets/images/hero.png': '64x64',
      'assets/images/hero_small.png': '32x32',
    });
    expect(scaled.single.message, contains('2.0x'));
  });

  test('same size, different bytes, same look is SIMILAR_ASSETS', () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/images/']))
      ..png('assets/images/banner.png', width: 64, height: 64)
      ..png('assets/images/banner_reexport.png',
          width: 64, height: 64, tweakPixel: 7)
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);

    expect(findingsWithCode(result, FindingCode.scaledVariant), isEmpty);
    final similar = findingsWithCode(result, FindingCode.similarAssets);
    expect(similar, hasLength(1));
    expect(similar.single.data['count'], 2);
  });

  test('visually different images are not grouped', () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/images/']))
      ..png('assets/images/light.png', pattern: 'gradient')
      ..png('assets/images/dark.png', pattern: 'reverse')
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);

    expect(findingsWithCode(result, FindingCode.similarAssets), isEmpty);
    expect(findingsWithCode(result, FindingCode.scaledVariant), isEmpty);
  });

  test('a legitimate 2.0x variant is not flagged as a near-duplicate',
      () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/images/']))
      ..png('assets/images/icon.png', width: 32, height: 32)
      ..png('assets/images/2.0x/icon.png', width: 64, height: 64)
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);

    expect(result.findings, isEmpty,
        reason: 'variants are supposed to look identical to their parent');
  });

  test('SVGs matching after normalization are grouped', () async {
    const geometry = 'M10.5 20.25 L30.75 40.5 L50.25 10.75 Z';
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/icons/']))
      ..file('assets/icons/star.svg',
          '<svg viewBox="0 0 64 64"><path id="a" d="$geometry"/></svg>')
      ..file('assets/icons/star_export.svg', '''
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by a design tool -->
<svg viewBox="0 0 64 64">
  <path id="Layer_1-2" d="$geometry"/>
</svg>
''')
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);
    final svgs = findingsWithCode(result, FindingCode.similarSvg);

    expect(svgs, hasLength(1));
    expect(svgs.single.data['normalizedIdentical'], isTrue);
    expect(svgs.single.relatedPaths, <String>['assets/icons/star_export.svg']);
  });

  test('unrelated SVGs are not grouped', () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/icons/']))
      ..file('assets/icons/triangle.svg',
          '<svg viewBox="0 0 64 64"><path d="M0 0 L64 0 L32 64 Z"/></svg>')
      ..file('assets/icons/line.svg',
          '<svg viewBox="0 0 64 64"><path d="M4 4 H60"/></svg>')
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(project, checks: <Check>[const SimilarCheck()]);

    expect(findingsWithCode(result, FindingCode.similarSvg), isEmpty);
  });

  test('files above --max-hash-size are skipped rather than compared',
      () async {
    project
      ..file('pubspec.yaml',
          flutterPubspec(name: 'my_app', assets: <String>['assets/images/']))
      ..png('assets/images/a.png', width: 64, height: 64)
      ..png('assets/images/b.png', width: 32, height: 32)
      ..file('lib/main.dart', 'void main() {}');

    final result = await audit(
      project,
      checks: <Check>[const SimilarCheck()],
      configure: (AssetGuardConfig c) => c.copyWith(maxHashSizeBytes: 10),
    );

    expect(result.findings, isEmpty);
    expect(result.context.content.skippedForSize, hasLength(2));
  });
}
